version: '3.3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'youtube'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'developer_123'
      MYSQL_ROOT_PASSWORD: 'root_123'
    ports:
      - '6333:3306'
    expose:
      - '6333'
    volumes:
      - ./mysql_vol:/var/lib/mysql
